steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/ongakuconnection/ongkconn', '.']
    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/ongakuconnection/ongkconn']
    # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'ongakconnbe', '--image', 'gcr.io/ongakuconnection/ongkconn', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated']